/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bmdb.view.extra;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.bmdb.view.Administration;
import org.bmdb.view.Credits;

/**
 *
 * @author duarteduarte
 */
public class bananaV2 extends javax.swing.JFrame {

    final ImageIcon icon = new ImageIcon("images/BananaLOGOpequeno.png");

    /**
     * Creates new form bananaV2
     */
    public bananaV2() {
        initComponents();
        //cores
        this.getContentPane().setBackground(Color.lightGray);
        jPanel1filme.setBackground(Color.lightGray);
        jPanel2Actores.setBackground(Color.lightGray);
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);
        jLabel5.setForeground(Color.black);
        jLabel7.setForeground(Color.black);
        jLabel8.setForeground(Color.black);
        jButton1.setBackground(Color.lightGray);
        jButton2.setBackground(Color.lightGray);
        jLabel6.setBackground(Color.black);
        //fim de cores



        jPanel1filme.setVisible(false);
        jPanel2Actores.setVisible(false);
        jFormattedTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jPanel2Actores.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFTF_user = new javax.swing.JFormattedTextField();
        jPF_user = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JRadioButton();
        jcb2 = new javax.swing.JRadioButton();
        jcb3 = new javax.swing.JRadioButton();
        jcb4 = new javax.swing.JRadioButton();
        jcb7 = new javax.swing.JRadioButton();
        jcb8 = new javax.swing.JRadioButton();
        jcb9 = new javax.swing.JRadioButton();
        jcb5 = new javax.swing.JRadioButton();
        jcb6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1filme = new javax.swing.JPanel();
        jButtonAdicionarFilme = new javax.swing.JButton();
        jButtonRemoverFilme = new javax.swing.JButton();
        jButtonAlterarFilme = new javax.swing.JButton();
        jButtonVerFilme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2Actores = new javax.swing.JPanel();
        jButtonAdicionarActor = new javax.swing.JButton();
        jButtonRemoverActor = new javax.swing.JButton();
        jButtonAlterarActor = new javax.swing.JButton();
        jButtonVerActor = new javax.swing.JButton();
        borderImagemActor = new javax.swing.JPanel();
        imagemActor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaActores = new javax.swing.JList();
        fnomeActor = new javax.swing.JFormattedTextField();
        fnomeActorVerifica = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        fPremiosVerifica = new javax.swing.JCheckBox();
        fOscaresVerifica = new javax.swing.JCheckBox();
        fMasculinoVerifica = new javax.swing.JCheckBox();
        fFemininoVerifica = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BananaMDB");
        setName("BananaMDB"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(812, 605));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/duarteduarte/NetBeansProjects/bgef/images/BananaLOGOpequeno.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setText("BananaMDB");

        jLabel3.setText("utilizador");

        jLabel4.setText("password");

        jFTF_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTF_userKeyPressed(evt);
            }
        });

        jPF_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPF_userKeyPressed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel5.setText("powered by BananaCorp®");

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("Filmes");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Actores");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Produtoras");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Realizadores");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("Generos");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setText("Noticias");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setText("Utilizadores");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setText("General Settings");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setText("Estatisticas");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setText("Connection");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Benvindo");

        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2ActionPerformed(evt);
            }
        });

        jcb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb3ActionPerformed(evt);
            }
        });

        jcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb4ActionPerformed(evt);
            }
        });

        jcb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb7ActionPerformed(evt);
            }
        });

        jcb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb8ActionPerformed(evt);
            }
        });

        jcb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb9ActionPerformed(evt);
            }
        });

        jcb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb5ActionPerformed(evt);
            }
        });

        jcb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setText("Contacts");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel8.setText("Administration");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jPanel1filme.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Filmes"));
        jPanel1filme.setMaximumSize(new java.awt.Dimension(524, 461));
        jPanel1filme.setSize(new java.awt.Dimension(609, 461));

        jButtonAdicionarFilme.setText("Adicionar");
        jButtonAdicionarFilme.setToolTipText("Pressione para inserir um novo");

        jButtonRemoverFilme.setText("Remover");
        jButtonRemoverFilme.setToolTipText("Pressione para remover um existente");

        jButtonAlterarFilme.setText("Alterar");
        jButtonAlterarFilme.setToolTipText("Pressione para alterar um filme");

        jButtonVerFilme.setText("Ver");
        jButtonVerFilme.setToolTipText("Pressione para consultar existentes");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jLabel9.setText("Filtro:");

        jCheckBox1.setText("Oscares");

        jCheckBox2.setText("Ano");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Premios");

        jCheckBox4.setText("Titulo");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Super Budget");

        jCheckBox6.setText("Super Gross");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel10.setText("imagem");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel10)
                .add(0, 68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel10)
                .add(0, 120, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1filmeLayout = new org.jdesktop.layout.GroupLayout(jPanel1filme);
        jPanel1filme.setLayout(jPanel1filmeLayout);
        jPanel1filmeLayout.setHorizontalGroup(
            jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1filmeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonAlterarFilme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonAdicionarFilme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonRemoverFilme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonVerFilme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jCheckBox4)
                    .add(jFormattedTextField1)
                    .add(jCheckBox3)
                    .add(jCheckBox1)
                    .add(jCheckBox2)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBox5)
                    .add(jCheckBox6)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1filmeLayout.setVerticalGroup(
            jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1filmeLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1filmeLayout.createSequentialGroup()
                        .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1filmeLayout.createSequentialGroup()
                                .add(jButtonAdicionarFilme)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonRemoverFilme)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonAlterarFilme)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonVerFilme))
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1filmeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jCheckBox4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFormattedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox6)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1)))
        );

        jPanel2Actores.setBorder(javax.swing.BorderFactory.createTitledBorder("Actores"));
        jPanel2Actores.setMinimumSize(new java.awt.Dimension(461, 609));
        jPanel2Actores.setSize(new java.awt.Dimension(461, 609));

        jButtonAdicionarActor.setText("Adicionar");
        jButtonAdicionarActor.setToolTipText("Pressione para inserir um novo");

        jButtonRemoverActor.setText("Remover");
        jButtonRemoverActor.setToolTipText("Pressione para remover um existente");

        jButtonAlterarActor.setText("Alterar");
        jButtonAlterarActor.setToolTipText("Pressione para alterar um filme");

        jButtonVerActor.setText("Ver");
        jButtonVerActor.setToolTipText("Pressione para consultar existentes");

        borderImagemActor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        imagemActor.setText("imagem");

        org.jdesktop.layout.GroupLayout borderImagemActorLayout = new org.jdesktop.layout.GroupLayout(borderImagemActor);
        borderImagemActor.setLayout(borderImagemActorLayout);
        borderImagemActorLayout.setHorizontalGroup(
            borderImagemActorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(borderImagemActorLayout.createSequentialGroup()
                .add(imagemActor)
                .add(0, 68, Short.MAX_VALUE))
        );
        borderImagemActorLayout.setVerticalGroup(
            borderImagemActorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(borderImagemActorLayout.createSequentialGroup()
                .add(imagemActor)
                .add(0, 120, Short.MAX_VALUE))
        );

        listaActores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaActores);

        fnomeActorVerifica.setText("Nome");
        fnomeActorVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnomeActorVerificaActionPerformed(evt);
            }
        });

        jLabel12.setText("Filtro:");

        fPremiosVerifica.setText("Premios");

        fOscaresVerifica.setText("Oscares");

        fMasculinoVerifica.setText("Masculino");

        fFemininoVerifica.setText("Feminino");

        org.jdesktop.layout.GroupLayout jPanel2ActoresLayout = new org.jdesktop.layout.GroupLayout(jPanel2Actores);
        jPanel2Actores.setLayout(jPanel2ActoresLayout);
        jPanel2ActoresLayout.setHorizontalGroup(
            jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2ActoresLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonAlterarActor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonAdicionarActor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonRemoverActor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonVerActor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(fnomeActorVerifica)
                        .add(fnomeActor)
                        .add(fPremiosVerifica)
                        .add(fOscaresVerifica)
                        .add(borderImagemActor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(fMasculinoVerifica)
                    .add(fFemininoVerifica))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 133, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2ActoresLayout.setVerticalGroup(
            jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2ActoresLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2ActoresLayout.createSequentialGroup()
                        .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel2ActoresLayout.createSequentialGroup()
                                .add(jButtonAdicionarActor)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonRemoverActor)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonAlterarActor)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonVerActor))
                            .add(borderImagemActor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2ActoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(fnomeActorVerifica))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fnomeActor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fPremiosVerifica)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fOscaresVerifica)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fMasculinoVerifica)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fFemininoVerifica)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel5)
                        .add(18, 18, 18)
                        .add(jLabel7)
                        .add(18, 18, 18)
                        .add(jLabel8)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jToggleButton10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(1, 1, 1)
                                .add(jPanel2Actores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .add(121, 121, 121))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel4)
                                            .add(jLabel3))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jPF_user)
                                            .add(jFTF_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(jcb1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jcb2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jcb3))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jcb4)
                                            .add(jcb7))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(jcb8)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jcb9))
                                            .add(layout.createSequentialGroup()
                                                .add(jcb5)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jcb6)))))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1filme, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jcb2)
                                    .add(jcb3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jcb6)
                                    .add(jcb5))
                                .add(6, 6, 6)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jcb9)
                                    .add(jcb8)))
                            .add(layout.createSequentialGroup()
                                .add(jcb1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jcb4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jcb7))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFTF_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jButton1)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButton2)
                                    .add(jPF_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6))))
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1filme, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(jToggleButton1)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton2)
                            .add(7, 7, 7)
                            .add(jToggleButton3)
                            .add(7, 7, 7)
                            .add(jToggleButton4)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton5)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton6)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton7)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton8)
                            .add(54, 54, 54)
                            .add(jToggleButton9)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jToggleButton10))
                        .add(jPanel2Actores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel7)
                    .add(jLabel8)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        changeColorsToOrange();
        jPanel1filme.setEnabled(true);
        jPanel1filme.setVisible(true);
        jPanel2Actores.setEnabled(false);
        jPanel2Actores.setVisible(false);


        // this.jPanel1 = toIncorporate;
        // this.jPanel1.setVisible(true);
        // this.jPanel1.setEnabled(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jFTF_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTF_userKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jFTF_userKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
        executaLogin(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPF_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPF_userKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jPF_userKeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Administration admin = new Administration(this);
        admin.setTitle("Administration");
        admin.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7KeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Credits credits = new Credits(this);
        credits.setTitle("Credits");
        credits.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb2ActionPerformed

    private void jcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb4ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb4ActionPerformed

    private void jcb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb5ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb5ActionPerformed

    private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb3ActionPerformed

    private void jcb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb6ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb6ActionPerformed

    private void jcb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb7ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb7ActionPerformed

    private void jcb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb8ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);

    }//GEN-LAST:event_jcb8ActionPerformed
    private void jcb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb9ActionPerformed
        // TODO add your handling code here:
        executaLogin(1);
    }//GEN-LAST:event_jcb9ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()) {
            jFormattedTextField1.setVisible(true);
        } else {
            jFormattedTextField1.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jTextField2.setVisible(true);
        } else {
            jTextField2.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
        jPanel1filme.setEnabled(false);
        jPanel1filme.setVisible(false);
        jPanel2Actores.setEnabled(true);
        jPanel2Actores.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        changeColorsToOrange();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnomeActorVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnomeActorVerificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnomeActorVerificaActionPerformed

    private void changeColorsToOrange() {
        if (jToggleButton9.isSelected()) {
            this.getContentPane().setBackground(Color.BLACK);
            jLabel2.setForeground(Color.orange);
            jLabel3.setForeground(Color.orange);
            jLabel5.setForeground(Color.orange);
            jLabel7.setForeground(Color.orange);
            jLabel8.setForeground(Color.orange);
            jButton1.setBackground(Color.orange);
            jButton2.setBackground(Color.orange);
            jLabel6.setBackground(Color.orange);
        } else {
            this.getContentPane().setBackground(Color.lightGray);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
            jLabel5.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
            jLabel8.setForeground(Color.black);
            jButton1.setBackground(Color.lightGray);
            jButton2.setBackground(Color.lightGray);
            jLabel6.setBackground(Color.black);
        }
    }

    private void executaLogin(int tipo) {
        boolean res = false;
        if (tipo == 0) {
            boolean user = jFTF_user.getText().equals("user");
            char[] pass = jPF_user.getPassword();
            StringBuffer password = new StringBuffer();
            for (char c : pass) {
                password.append(c);
            }
            if (user && password.toString().equals("pass")) {
                jLabel6.setText("Benvindo " + jFTF_user.getText() + "!");
                jLabel6.setVisible(true);
                res = true;
            }
        } else if (tipo == 1) {
            if (jcb1.isSelected() && jcb5.isSelected() && jcb7.isSelected() && !jcb2.isSelected() && !jcb3.isSelected()
                    && !jcb4.isSelected() && !jcb6.isSelected() && !jcb8.isSelected() && !jcb9.isSelected()) {
                res = true;
                jLabel6.setText("Benvindo " + jFTF_user.getText() + "!");
                jLabel6.setVisible(true);
            }
            if (res) {
                jPF_user.setText(null);
                jFTF_user.setText(null);
                jcb1.setSelected(false);
                jcb2.setSelected(false);
                jcb3.setSelected(false);
                jcb4.setSelected(false);
                jcb5.setSelected(false);
                jcb6.setSelected(false);
                jcb7.setSelected(false);
                jcb8.setSelected(false);
                jcb9.setSelected(false);
            } else if (tipo == 0) {
                jPF_user.setText(null);
                jFTF_user.setText(null);
                JOptionPane.showMessageDialog(this, "Autenticação inválida", "Error", JOptionPane.INFORMATION_MESSAGE, icon);

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


























                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bananaV2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bananaV2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bananaV2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bananaV2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bananaV2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borderImagemActor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox fFemininoVerifica;
    private javax.swing.JCheckBox fMasculinoVerifica;
    private javax.swing.JCheckBox fOscaresVerifica;
    private javax.swing.JCheckBox fPremiosVerifica;
    private javax.swing.JFormattedTextField fnomeActor;
    private javax.swing.JCheckBox fnomeActorVerifica;
    private javax.swing.JLabel imagemActor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarActor;
    private javax.swing.JButton jButtonAdicionarFilme;
    private javax.swing.JButton jButtonAlterarActor;
    private javax.swing.JButton jButtonAlterarFilme;
    private javax.swing.JButton jButtonRemoverActor;
    private javax.swing.JButton jButtonRemoverFilme;
    private javax.swing.JButton jButtonVerActor;
    private javax.swing.JButton jButtonVerFilme;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JFormattedTextField jFTF_user;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPF_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1filme;
    private javax.swing.JPanel jPanel2Actores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JRadioButton jcb1;
    private javax.swing.JRadioButton jcb2;
    private javax.swing.JRadioButton jcb3;
    private javax.swing.JRadioButton jcb4;
    private javax.swing.JRadioButton jcb5;
    private javax.swing.JRadioButton jcb6;
    private javax.swing.JRadioButton jcb7;
    private javax.swing.JRadioButton jcb8;
    private javax.swing.JRadioButton jcb9;
    private javax.swing.JList listaActores;
    // End of variables declaration//GEN-END:variables
}
